apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  namespace: bot-marketplace
  labels:
    app: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: bot-marketplace-celery:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bot-marketplace-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: bot-marketplace-secrets
              key: REDIS_URL
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: bot-marketplace-config
              key: ENVIRONMENT
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: bot-marketplace-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: bot-marketplace-config
              key: CELERY_RESULT_BACKEND
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - utils.celery_app
            - inspect
            - ping
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - celery
            - -A
            - utils.celery_app
            - inspect
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: logs-volume
        emptyDir: {} 